# Generated by Django 4.2.2 on 2023-09-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_post', models.CharField(max_length=100)),
                ('descricao_post', models.CharField(max_length=255)),
                ('data_post', models.DateTimeField(verbose_name='Data publicado')),
            ],
        ),
    ]
